"""Closed requirements registry: statement, applicability and proving tier."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class Requirement:
    id: str
    statement: str
    source: str
    applicability: str
    proving_tests: tuple[str, ...]
    acceptance_methods: tuple[str, ...]
    minimum_tier: int


def _requirement(
    identifier: str,
    statement: str,
    rule: str,
    applicable: str,
    methods: tuple[str, ...],
    tier: int,
    tests: tuple[str, ...],
) -> Requirement:
    return Requirement(
        identifier, statement, "review-2026-10-05:" + rule, applicable, tests, methods, tier
    )


REQUIREMENTS = (
    _requirement(
        "HOST-DATA",
        "Host values stay outside framework code.",
        "D1",
        "all",
        ("schema-tests",),
        1,
        ("test_generic_guard_catches_private_site_literals_without_echoing_them",),
    ),
    _requirement(
        "DATA-ONLY",
        "An instance is canonical closed data, never executable configuration.",
        "D2",
        "all",
        ("schema-tests",),
        1,
        ("test_instance_rejects_code_and_unknown_keys",),
    ),
    _requirement(
        "SOURCE-AUTHORSHIP",
        "Each setting has exactly one declared author at every migration step.",
        "Rule1",
        "all",
        ("fixture-parity",),
        1,
        ("test_authoring_claims_cannot_overlap",),
    ),
    _requirement(
        "FRAMEWORK-PIN",
        "The framework artifact, revision and dependency lock are content-pinned.",
        "D3",
        "all",
        ("schema-tests",),
        1,
        ("test_release_pin_verifies_exact_artifact",),
    ),
    _requirement(
        "NAMES-PRESERVED",
        "Existing installed names and state paths remain pinned during migration.",
        "D4",
        "all",
        ("fixture-parity",),
        1,
        ("test_names_are_pinned_or_namespace_derived",),
    ),
    _requirement(
        "PLATFORM-SUPPORT",
        "Candidate parser compatibility is distinct from accepted native host support.",
        "D6",
        "all",
        ("root-runtime-observer",),
        2,
        ("test_candidate_platform_is_not_hardware_acceptance",),
    ),
    _requirement(
        "HOST-CAPABILITIES",
        "Hardware, encryption, login, power and coexistence facts are observed separately.",
        "D5",
        "all",
        ("darwin-cli",),
        2,
        ("test_missing_host_facts_remain_unknown",),
    ),
    _requirement(
        "LAN-IDENTITY",
        "Exactly one declared IPv4 LAN has current address and stable interface identity proof.",
        "D8",
        "all",
        ("darwin-cli",),
        2,
        (
            "test_instance_has_one_lan_and_no_live_guest_addresses",
            "test_lan_identity_needs_the_declared_current_address_and_adapter",
        ),
    ),
    _requirement(
        "IPV4-SCOPE",
        "IPv6 is outside the custom policy, not asserted blocked.",
        "D8",
        "all",
        ("schema-tests",),
        1,
        ("test_instance_has_one_lan_and_no_live_guest_addresses",),
    ),
    _requirement(
        "WORKLOAD-CONTRACTS",
        "Workload contracts preserve image, mounts, resources, kernel and application data.",
        "5.1",
        "workloads",
        ("fixture-parity",),
        1,
        ("test_workload_contract_hash_and_closed_data",),
    ),
    _requirement(
        "COMPONENT-HEALTH",
        "A component has separate health; its failure is not workload restart authority.",
        "5.1",
        "components",
        ("schema-tests",),
        1,
        ("test_failed_component_is_reported_separately_and_authorizes_no_restart",),
    ),
    _requirement(
        "PORT-RANGES",
        "Each automatic socket range is declared once and shared by exact reference.",
        "Rule9",
        "bounded-udp",
        ("schema-tests",),
        1,
        ("test_udp_range_is_one_named_reference",),
    ),
    _requirement(
        "PORT-COLLISIONS",
        "Publications and UDP-return claims do not overlap.",
        "Rule1",
        "transport",
        ("rule-readback",),
        2,
        ("test_instance_rejects_overlapping_port_claims",),
    ),
    _requirement(
        "LIFECYCLE-WRITERS",
        "Container API writers and their authority residual are explicit.",
        "Rule3",
        "api-writers",
        ("process-inventory",),
        2,
        ("test_unsigned_lifecycle_residual_is_not_accepted",),
    ),
    _requirement(
        "ROOT-INDEPENDENCE",
        "No new unprivileged host command invokes or supplies an action to root.",
        "Rule3",
        "all",
        ("schema-tests",),
        1,
        ("test_host_entrypoint_never_contacts_network",),
    ),
    _requirement(
        "ROOT-ADMISSION",
        "Root independently approves resolved parameters, never a reused profile name.",
        "Rule2",
        "root-transport",
        ("rule-readback",),
        2,
        ("test_profile_digest_binds_resolved_parameters",),
    ),
    _requirement(
        "ROOT-HARD-BOUNDS",
        "No profile widens interface, IPv4 scope or admitted rule shape.",
        "Rule2",
        "root-transport",
        ("first-packet",),
        3,
        ("test_unknown_strategy_or_version_is_rejected",),
    ),
    _requirement(
        "BOUNDED-IDENTITY",
        "Direct guest targets need a signed residual and a demonstrated withdrawal bound.",
        "Rule4",
        "bounded",
        ("state-drain",),
        3,
        ("test_no_guessed_withdrawal_bound",),
    ),
    _requirement(
        "PAUSE-PRESERVED",
        "Pause and unrelated holder suspensions survive installation and rollback.",
        "Rule5",
        "all",
        ("fixture-parity",),
        1,
        (
            "test_user_install_preserves_pause_and_definitions",
            "test_upgrade_and_explicit_rollback_preserves_current_pause",
        ),
    ),
    _requirement(
        "UNKNOWN-NO-RECOVERY",
        "Unknown, stale, busy or timed-out observations never authorize recovery.",
        "Rule6",
        "all",
        ("schema-tests",),
        1,
        ("test_unknown_observations_never_become_healthy",),
    ),
    _requirement(
        "DISCOVERY-PUBLICATION",
        "Export corresponds to the announcing workload's exact publication.",
        "Rule8",
        "exports",
        ("application-connect",),
        5,
        ("test_export_needs_own_publication",),
    ),
    _requirement(
        "DISCOVERY-IMPORT",
        (
            "Apple-media import needs a cold scan or changed/new receiver; "
            "warm-cache reload proves no import."
        ),
        "9",
        "imports",
        ("cold-application-scan", "receiver-change"),
        5,
        ("test_transport_success_does_not_prove_discovery",),
    ),
    _requirement(
        "IMPORT-VISIBILITY",
        "The owner explicitly accepts the visibility of imported discovery records.",
        "3.2",
        "imports",
        ("schema-tests",),
        1,
        ("test_import_visibility_requires_current_explicit_owner_decision",),
    ),
    _requirement(
        "DISCOVERY-LEASES",
        "A genuine projection has interface, identity and independent age proof.",
        "Rule8",
        "discovery",
        ("application-connect",),
        5,
        ("test_transport_success_does_not_prove_discovery",),
    ),
    _requirement(
        "CONSENT-IDENTITY",
        "The real user LaunchAgent's Local Network identity is accepted.",
        "Rule7",
        "discovery",
        ("local-network-consent",),
        3,
        (
            "test_consent_identity_needs_a_current_launch_agent_identity_fact",
            "test_consent_acceptance_needs_the_launch_agent_context",
        ),
    ),
    _requirement(
        "UDP-FIRST-PACKET",
        "The first outbound request and reply preserve ports within the admitted range.",
        "9",
        "bounded-udp",
        ("first-packet",),
        3,
        (
            "test_admitted_preview_splits_udp_static_nat_from_targetless_rdr",
            "test_rule_renderer_static_port_and_targetless_rdr",
        ),
    ),
    _requirement(
        "DNS-CLIENT-IDENTITY",
        "The resolver application sees the originating client identity.",
        "5.1",
        "resolver",
        ("dns-client-identity",),
        5,
        (
            "test_resolver_requirements_apply_only_to_a_resolver_workload",
            "test_native_dns_fallback_supports_tcp_and_udp_and_reports_degradation",
        ),
    ),
    _requirement(
        "HEARD-AUDIO",
        "A person confirms audible playback for the exact current policy and runtime.",
        "9",
        "imports",
        ("heard-audio",),
        5,
        ("test_receipt_never_proves_live_application",),
    ),
    _requirement(
        "MULTI-RECEIVER",
        "Representative multiple receiver capacity is recorded without widening policy.",
        "Rule9",
        "imports",
        ("port-budget",),
        5,
        ("test_missing_acceptance_stays_unverified",),
    ),
    _requirement(
        "BOOT-RECOVERY",
        "An accepted unattended boot restores workloads and DNS within the chosen limit.",
        "10",
        "all",
        ("unattended-reboot",),
        4,
        ("test_filevault_on_does_not_fulfil_unattended_recovery",),
    ),
    _requirement(
        "RESTORE-REHEARSAL",
        "Off-host recovery material was read back and one restore rehearsed.",
        "10",
        "all",
        ("restore-rehearsal",),
        4,
        ("test_missing_acceptance_stays_unverified",),
    ),
    _requirement(
        "APPLICATION-PRESERVED",
        "Application settings, secrets, pairings and storage are not edited by new host tools.",
        "5.1",
        "all",
        ("schema-tests",),
        1,
        ("test_host_commands_do_not_change_state",),
    ),
    _requirement(
        "NO-EXTRA-WORKLOAD",
        "The read-only framework adds no VM, networking workload or daemon.",
        "5.1",
        "all",
        ("process-inventory",),
        2,
        ("test_host_entrypoint_never_contacts_network",),
    ),
    _requirement(
        "COEXISTENCE",
        "Foreign rules, listeners, OS firewall and other services remain independently owned.",
        "D5",
        "all",
        ("rule-readback",),
        2,
        ("test_host_commands_do_not_change_state",),
    ),
    _requirement(
        "OWNER-CONFORMANCE",
        "Each owner renders byte-identically to its frozen baseline before authority changes.",
        "5.2",
        "all",
        ("fixture-parity",),
        1,
        (
            "test_even_headers_whitespace_and_final_newline_break_parity",
            "test_exact_owner_flip_changes_only_provenance_and_not_inputs",
        ),
    ),
    _requirement(
        "OWNER-ROLLBACK",
        "Owner rollback restores the reviewed release/instance pair and current pause.",
        "5.1",
        "all",
        ("restore-rehearsal",),
        4,
        ("test_upgrade_and_explicit_rollback_preserves_current_pause",),
    ),
    _requirement(
        "EXIT-STRATEGIES",
        "Each custom strategy states the upstream capability that retires it.",
        "5.1",
        "all",
        ("schema-tests",),
        1,
        ("test_registry_has_sources_proofs_and_retirement",),
    ),
    _requirement(
        "NO-LOCAL-NETWORK",
        "Validation, preflight, status, plan, check and report make no LAN operation.",
        "Rule7",
        "all",
        ("schema-tests",),
        1,
        ("test_host_entrypoint_never_contacts_network",),
    ),
    _requirement(
        "PORT-BUDGET",
        "Idle and representative-load UDP socket counts are observed independently.",
        "Rule9",
        "bounded-udp",
        ("port-budget",),
        3,
        ("test_port_budget_counts_are_typed_and_observed_independently",),
    ),
    _requirement(
        "RUNTIME-DNS",
        "Vendor runtime DNS settings are observed and preserved, never silently changed.",
        "5.1",
        "resolver",
        ("darwin-cli",),
        2,
        (
            "test_runtime_dns_settings_are_unknown_until_observed",
            "test_host_entrypoint_never_contacts_network",
        ),
    ),
    _requirement(
        "CURRENT-OBSERVATIONS",
        "Every owner has its own age, reason and generation; receipts are historical evidence.",
        "Rule6",
        "all",
        ("schema-tests",),
        1,
        ("test_unknown_observations_never_become_healthy",),
    ),
    _requirement(
        "RENDER-INDEPENDENCE",
        "A different synthetic host validates independently without host-name branches.",
        "D1",
        "all",
        ("fixture-parity",),
        1,
        ("test_synthetic_variants_validate_without_native_support",),
    ),
)


def requirement(identifier: str) -> Requirement:
    for item in REQUIREMENTS:
        if item.id == identifier:
            return item
    raise ValueError("unknown requirement identifier")
